name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose
      run: cd server && docker-compose up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Check running containers
      run: docker ps -a
    - name: Check if container is alive
      run: cd server && docker-compose exec -T board-detection echo "I am up"
    - name: Get Failed logs
      if: ${{ failure() }}
      run: cd server && docker-compose logs
